# Generated by scripts/generate-media-formats.py. Do not edit by hand.
# Source: /home/runner/work/LM-Bridge-DEV/LM-Bridge-DEV/data/media_formats_meta.json

MEDIA_FORMATS_META = {
  "digital": [
    {
      "name": "digital_hi_res",
      "formats": [
        "Blu-ray",
        "Blu-ray-R",
        "HD-DVD",
        "DVD-Audio",
        "SHM-SACD",
        "SACD",
        "Hybrid SACD (SACD layer)",
        "Hybrid SACD",
        "DualDisc (DVD-Audio side)",
        "DVDplus (DVD-Audio side)"
      ]
    },
    {
      "name": "digital_cd_quality",
      "formats": [
        "DTS CD",
        "HDCD",
        "DAT",
        "Compact Disc",
        "8cm CD",
        "SHM-CD",
        "HQCD",
        "Blu-spec CD",
        "Minimax CD",
        "Enhanced CD",
        "Mixed Mode CD",
        "Copy Control CD",
        "Data CD",
        "CD-R",
        "CD+G",
        "8cm CD+G",
        "Hybrid SACD (CD layer)",
        "DualDisc (CD side)",
        "DVDplus (CD side)",
        "CDV"
      ]
    },
    {
      "name": "digital_media",
      "formats": [
        "Digital Media"
      ]
    },
    {
      "name": "digital_video_optical",
      "formats": [
        "DVD-Video",
        "DVD",
        "DualDisc (DVD-Video side)",
        "DVDplus (DVD-Video side)",
        "DualDisc",
        "DVDplus",
        "SVCD",
        "VCD",
        "UMD"
      ]
    },
    {
      "name": "digital_compressed_or_legacy",
      "formats": [
        "DCC",
        "MiniDisc"
      ]
    },
    {
      "name": "digital_legacy_media",
      "formats": [
        "USB Flash Drive",
        "SD card",
        "Download Card",
        "slotMusic",
        "Zip Disk",
        "3.5\" Floppy Disk",
        "5.25\" Floppy Disk",
        "Floppy Disk",
        "Playbutton"
      ]
    },
    {
      "name": "digital_other_unknown",
      "formats": [
        "Other",
        "Unknown"
      ]
    }
  ],
  "analog": [
    {
      "name": "analog_vinyl",
      "formats": [
        "Vinyl",
        "12\" Vinyl",
        "10\" Vinyl",
        "7\" Vinyl"
      ]
    },
    {
      "name": "analog_other_discs",
      "formats": [
        "Edison Diamond Disc",
        "Pathé disc",
        "VinylDisc",
        "Flexi-disc",
        "7\" Flexi-disc"
      ]
    },
    {
      "name": "analog_tape",
      "formats": [
        "Reel-to-reel",
        "Cassette",
        "Cartridge",
        "Microcassette",
        "HiPac",
        "PlayTape"
      ]
    },
    {
      "name": "analog_video",
      "formats": [
        "LaserDisc",
        "12\" LaserDisc",
        "8\" LaserDisc",
        "Betamax",
        "VHS",
        "VHD",
        "CED"
      ]
    },
    {
      "name": "analog_acetate",
      "formats": [
        "Acetate",
        "12\" Acetate",
        "10\" Acetate",
        "7\" Acetate"
      ]
    },
    {
      "name": "analog_shellac",
      "formats": [
        "Shellac",
        "12\" Shellac",
        "10\" Shellac",
        "7\" Shellac"
      ]
    },
    {
      "name": "analog_mechanical",
      "formats": [
        "Tefifon",
        "Wax Cylinder",
        "Piano roll"
      ]
    }
  ]
}
META_ORDER = {
  "digital": [
    "digital_hi_res",
    "digital_cd_quality",
    "digital_media",
    "digital_video_optical",
    "digital_compressed_or_legacy",
    "digital_legacy_media",
    "digital_other_unknown"
  ],
  "analog": [
    "analog_vinyl",
    "analog_other_discs",
    "analog_tape",
    "analog_video",
    "analog_acetate",
    "analog_shellac",
    "analog_mechanical"
  ]
}
ALIAS_MAP = {
  "digital_hi_res": [
    "blu-ray",
    "blu-ray-r",
    "hd-dvd",
    "dvd-audio",
    "shm-sacd",
    "sacd",
    "hybrid sacd (sacd layer)",
    "hybrid sacd",
    "dualdisc (dvd-audio side)",
    "dvdplus (dvd-audio side)"
  ],
  "digital_cd_quality": [
    "dts cd",
    "hdcd",
    "dat",
    "compact disc",
    "8cm cd",
    "shm-cd",
    "hqcd",
    "blu-spec cd",
    "minimax cd",
    "enhanced cd",
    "mixed mode cd",
    "copy control cd",
    "data cd",
    "cd-r",
    "cd+g",
    "8cm cd+g",
    "hybrid sacd (cd layer)",
    "dualdisc (cd side)",
    "dvdplus (cd side)",
    "cdv"
  ],
  "digital_media": [
    "digital media"
  ],
  "digital_video_optical": [
    "dvd-video",
    "dvd",
    "dualdisc (dvd-video side)",
    "dvdplus (dvd-video side)",
    "dualdisc",
    "dvdplus",
    "svcd",
    "vcd",
    "umd"
  ],
  "digital_compressed_or_legacy": [
    "dcc",
    "minidisc"
  ],
  "digital_legacy_media": [
    "usb flash drive",
    "sd card",
    "download card",
    "slotmusic",
    "zip disk",
    "3.5\" floppy disk",
    "5.25\" floppy disk",
    "floppy disk",
    "playbutton"
  ],
  "digital_other_unknown": [
    "other",
    "unknown"
  ],
  "digital": [
    "blu-ray",
    "blu-ray-r",
    "hd-dvd",
    "dvd-audio",
    "shm-sacd",
    "sacd",
    "hybrid sacd (sacd layer)",
    "hybrid sacd",
    "dualdisc (dvd-audio side)",
    "dvdplus (dvd-audio side)",
    "dts cd",
    "hdcd",
    "dat",
    "compact disc",
    "8cm cd",
    "shm-cd",
    "hqcd",
    "blu-spec cd",
    "minimax cd",
    "enhanced cd",
    "mixed mode cd",
    "copy control cd",
    "data cd",
    "cd-r",
    "cd+g",
    "8cm cd+g",
    "hybrid sacd (cd layer)",
    "dualdisc (cd side)",
    "dvdplus (cd side)",
    "cdv",
    "digital media",
    "dvd-video",
    "dvd",
    "dualdisc (dvd-video side)",
    "dvdplus (dvd-video side)",
    "dualdisc",
    "dvdplus",
    "svcd",
    "vcd",
    "umd",
    "dcc",
    "minidisc",
    "usb flash drive",
    "sd card",
    "download card",
    "slotmusic",
    "zip disk",
    "3.5\" floppy disk",
    "5.25\" floppy disk",
    "floppy disk",
    "playbutton",
    "other",
    "unknown"
  ],
  "analog_vinyl": [
    "vinyl",
    "12\" vinyl",
    "10\" vinyl",
    "7\" vinyl"
  ],
  "analog_other_discs": [
    "edison diamond disc",
    "pathé disc",
    "vinyldisc",
    "flexi-disc",
    "7\" flexi-disc"
  ],
  "analog_tape": [
    "reel-to-reel",
    "cassette",
    "cartridge",
    "microcassette",
    "hipac",
    "playtape"
  ],
  "analog_video": [
    "laserdisc",
    "12\" laserdisc",
    "8\" laserdisc",
    "betamax",
    "vhs",
    "vhd",
    "ced"
  ],
  "analog_acetate": [
    "acetate",
    "12\" acetate",
    "10\" acetate",
    "7\" acetate"
  ],
  "analog_shellac": [
    "shellac",
    "12\" shellac",
    "10\" shellac",
    "7\" shellac"
  ],
  "analog_mechanical": [
    "tefifon",
    "wax cylinder",
    "piano roll"
  ],
  "analog": [
    "vinyl",
    "12\" vinyl",
    "10\" vinyl",
    "7\" vinyl",
    "edison diamond disc",
    "pathé disc",
    "vinyldisc",
    "flexi-disc",
    "7\" flexi-disc",
    "reel-to-reel",
    "cassette",
    "cartridge",
    "microcassette",
    "hipac",
    "playtape",
    "laserdisc",
    "12\" laserdisc",
    "8\" laserdisc",
    "betamax",
    "vhs",
    "vhd",
    "ced",
    "acetate",
    "12\" acetate",
    "10\" acetate",
    "7\" acetate",
    "shellac",
    "12\" shellac",
    "10\" shellac",
    "7\" shellac",
    "tefifon",
    "wax cylinder",
    "piano roll"
  ]
}
PRIORITY_DIGITAL_FIRST = [
  "blu-ray",
  "blu-ray-r",
  "hd-dvd",
  "dvd-audio",
  "shm-sacd",
  "sacd",
  "hybrid sacd (sacd layer)",
  "hybrid sacd",
  "dualdisc (dvd-audio side)",
  "dvdplus (dvd-audio side)",
  "dts cd",
  "hdcd",
  "dat",
  "compact disc",
  "8cm cd",
  "shm-cd",
  "hqcd",
  "blu-spec cd",
  "minimax cd",
  "enhanced cd",
  "mixed mode cd",
  "copy control cd",
  "data cd",
  "cd-r",
  "cd+g",
  "8cm cd+g",
  "hybrid sacd (cd layer)",
  "dualdisc (cd side)",
  "dvdplus (cd side)",
  "cdv",
  "digital media",
  "dvd-video",
  "dvd",
  "dualdisc (dvd-video side)",
  "dvdplus (dvd-video side)",
  "dualdisc",
  "dvdplus",
  "svcd",
  "vcd",
  "umd",
  "dcc",
  "minidisc",
  "usb flash drive",
  "sd card",
  "download card",
  "slotmusic",
  "zip disk",
  "3.5\" floppy disk",
  "5.25\" floppy disk",
  "floppy disk",
  "playbutton",
  "other",
  "unknown",
  "vinyl",
  "12\" vinyl",
  "10\" vinyl",
  "7\" vinyl",
  "edison diamond disc",
  "pathé disc",
  "vinyldisc",
  "flexi-disc",
  "7\" flexi-disc",
  "reel-to-reel",
  "cassette",
  "cartridge",
  "microcassette",
  "hipac",
  "playtape",
  "laserdisc",
  "12\" laserdisc",
  "8\" laserdisc",
  "betamax",
  "vhs",
  "vhd",
  "ced",
  "acetate",
  "12\" acetate",
  "10\" acetate",
  "7\" acetate",
  "shellac",
  "12\" shellac",
  "10\" shellac",
  "7\" shellac",
  "tefifon",
  "wax cylinder",
  "piano roll"
]
PRIORITY_ANALOG_FIRST = [
  "vinyl",
  "12\" vinyl",
  "10\" vinyl",
  "7\" vinyl",
  "edison diamond disc",
  "pathé disc",
  "vinyldisc",
  "flexi-disc",
  "7\" flexi-disc",
  "reel-to-reel",
  "cassette",
  "cartridge",
  "microcassette",
  "hipac",
  "playtape",
  "laserdisc",
  "12\" laserdisc",
  "8\" laserdisc",
  "betamax",
  "vhs",
  "vhd",
  "ced",
  "acetate",
  "12\" acetate",
  "10\" acetate",
  "7\" acetate",
  "shellac",
  "12\" shellac",
  "10\" shellac",
  "7\" shellac",
  "tefifon",
  "wax cylinder",
  "piano roll",
  "blu-ray",
  "blu-ray-r",
  "hd-dvd",
  "dvd-audio",
  "shm-sacd",
  "sacd",
  "hybrid sacd (sacd layer)",
  "hybrid sacd",
  "dualdisc (dvd-audio side)",
  "dvdplus (dvd-audio side)",
  "dts cd",
  "hdcd",
  "dat",
  "compact disc",
  "8cm cd",
  "shm-cd",
  "hqcd",
  "blu-spec cd",
  "minimax cd",
  "enhanced cd",
  "mixed mode cd",
  "copy control cd",
  "data cd",
  "cd-r",
  "cd+g",
  "8cm cd+g",
  "hybrid sacd (cd layer)",
  "dualdisc (cd side)",
  "dvdplus (cd side)",
  "cdv",
  "digital media",
  "dvd-video",
  "dvd",
  "dualdisc (dvd-video side)",
  "dvdplus (dvd-video side)",
  "dualdisc",
  "dvdplus",
  "svcd",
  "vcd",
  "umd",
  "dcc",
  "minidisc",
  "usb flash drive",
  "sd card",
  "download card",
  "slotmusic",
  "zip disk",
  "3.5\" floppy disk",
  "5.25\" floppy disk",
  "floppy disk",
  "playbutton",
  "other",
  "unknown"
]
