from __future__ import annotations

from typing import Dict, Any, List

PROVIDER_CAPABILITIES: Dict[str, Dict[str, Any]] = {
    "musicbrainz": {
        "display_name": "MusicBrainz",
        "capabilities": [
            "artist_metadata",
            "artist_links",
            "discography",
            "album_metadata",
            "album_art",
            "series",
            "id_redirects",
            "spotify_mapping",
        ],
        "auth": {"type": "none", "fields": []},
        "endpoints": {"base_url": "musicbrainz_db", "docs_url": ""},
        "moreinfo_url": "https://musicbrainz.org/",
        "rate_limit": {"requests_per_second": None, "requests_per_minute": None, "notes": "DB-backed"},
        "image_sizing": {"supports": False, "method": "", "original": "", "notes": ""},
        "supports_cache": True,
        "pricing": "unknown",
        "notes": "Cover art via CAA URLs; links parsed into typed sources.",
    },
    "cover_art_archive": {
        "display_name": "Cover Art Archive",
        "capabilities": ["album_art"],
        "auth": {"type": "none", "fields": []},
        "endpoints": {"base_url": "https://coverartarchive.org", "docs_url": ""},
        "moreinfo_url": "https://coverartarchive.org/",
        "rate_limit": {"requests_per_second": None, "requests_per_minute": None, "notes": "Best effort"},
        "image_sizing": {
            "supports": True,
            "method": "suffix",
            "sizes": ["250", "500", "1200"],
            "original": "no suffix",
            "notes": "Fixed size variants; original when no size suffix is used.",
        },
        "supports_cache": True,
        "pricing": "free",
        "notes": "Album cover art for MusicBrainz release groups.",
    },
    "fanart": {
        "display_name": "Fanart.tv",
        "capabilities": ["artist_images"],
        "auth": {"type": "api_key", "fields": ["FANART_KEY"]},
        "endpoints": {"base_url": "https://webservice.fanart.tv/v3.2/music", "docs_url": ""},
        "moreinfo_url": "https://fanart.tv/get-an-api-key/",
        "rate_limit": {"requests_per_second": None, "requests_per_minute": None, "notes": "Best effort"},
        "image_sizing": {"supports": False, "method": "", "original": "", "notes": ""},
        "supports_cache": True,
        "pricing": "free",
        "notes": "Artist artwork only (clearlogo, banner, fanart, poster).",
    },
    "theaudiodb": {
        "display_name": "TheAudioDB",
        "capabilities": ["artist_images"],
        "auth": {"type": "api_key", "fields": ["TADB_KEY"]},
        "endpoints": {"base_url": "https://www.theaudiodb.com/api/v2/json", "docs_url": ""},
        "moreinfo_url": "https://www.theaudiodb.com/api_guide.php",
        "rate_limit": {"requests_per_second": None, "requests_per_minute": None, "notes": "Best effort"},
        "image_sizing": {"supports": False, "method": "", "original": "", "notes": ""},
        "supports_cache": True,
        "pricing": "paid_required",
        "notes": "Artist artwork only (v2 premium API).",
    },
    "discogs": {
        "display_name": "Discogs",
        "capabilities": ["artist_images"],
        "auth": {"type": "token", "fields": ["DISCOGS_KEY"]},
        "endpoints": {"base_url": "https://api.discogs.com", "docs_url": ""},
        "moreinfo_url": "https://www.discogs.com/settings/developers",
        "rate_limit": {"requests_per_second": None, "requests_per_minute": None, "notes": "Best effort"},
        "image_sizing": {"supports": False, "method": "", "original": "", "notes": ""},
        "supports_cache": True,
        "pricing": "free",
        "notes": "Artist imagery and related metadata.",
    },
    "tidal": {
        "display_name": "TIDAL",
        "capabilities": ["artist_images"],
        "auth": {
            "type": "oauth_client",
            "fields": [
                "TIDAL_CLIENT_ID",
                "TIDAL_CLIENT_SECRET",
                "TIDAL_COUNTRY_CODE",
            ],
            "optional_fields": ["TIDAL_USER", "TIDAL_USER_PASSWORD"],
        },
        "endpoints": {"base_url": "https://openapi.tidal.com/v2", "docs_url": ""},
        "moreinfo_url": "https://developer.tidal.com/",
        "rate_limit": {"requests_per_second": None, "requests_per_minute": None, "notes": "Best effort"},
        "image_sizing": {"supports": False, "method": "", "original": "", "notes": ""},
        "supports_cache": True,
        "pricing": "paid_required",
        "notes": "Profile art via official API; user creds used for lookup fallback.",
    },
    "apple_music": {
        "display_name": "Apple Music",
        "capabilities": ["artist_images"],
        "auth": {"type": "none", "fields": []},
        "endpoints": {"base_url": "https://itunes.apple.com/search", "docs_url": ""},
        "moreinfo_url": "https://developer.apple.com/apple-music/",
        "rate_limit": {"requests_per_second": None, "requests_per_minute": None, "notes": "Best effort"},
        "image_sizing": {
            "supports": True,
            "method": "template",
            "sizes": ["{w}x{h}"],
            "original": "largest available",
            "notes": "Artwork URL embeds size as {w}x{h}.",
        },
        "supports_cache": True,
        "pricing": "free",
        "notes": "Artist artwork via iTunes Search API.",
    },
    "lastfm": {
        "display_name": "Last.fm",
        "capabilities": ["charts"],
        "auth": {"type": "api_key", "fields": ["LASTFM_KEY", "LASTFM_SECRET"]},
        "endpoints": {"base_url": "https://ws.audioscrobbler.com/2.0/", "docs_url": ""},
        "moreinfo_url": "https://www.last.fm/api/account/create",
        "rate_limit": {"requests_per_second": None, "requests_per_minute": None, "notes": "Best effort"},
        "image_sizing": {"supports": False, "method": "", "original": "", "notes": ""},
        "supports_cache": True,
        "pricing": "free",
        "notes": "Top artists/albums only.",
    },
}


def list_provider_capabilities() -> List[Dict[str, Any]]:
    return [PROVIDER_CAPABILITIES[key] | {"id": key} for key in sorted(PROVIDER_CAPABILITIES)]
